version: '3.9'

services:
  db:
    image: mongo:8.0.5-rc1-noble
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      #- mongodb-data:/data/db #PROD
      - ./mongodb-data:/data/db #DEV
    networks:
      - app-network

  backend:
    image: rfusaro12276/backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    image: rfusaro12276/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
